//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chat_api_desktop.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cliente()
        {
            this.Facturas = new HashSet<Facturas>();
        }
    
        public int clie_id { get; set; }
        public string clie_idtipoidentificacion { get; set; }
        public string clie_identificacion { get; set; }
        public string clie_nombre { get; set; }
        public string clie_apellidos { get; set; }
        public string clie_direccion { get; set; }
        public string clie_idsexo { get; set; }
        public string clie_telefono { get; set; }
        public string clie_barrio { get; set; }
        public string clie_codigo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facturas> Facturas { get; set; }
    }
}
