//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chat_api_desktop.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturas
    {
        public int id { get; set; }
        public Nullable<int> idcliente { get; set; }
        public Nullable<System.DateTime> fechaenvio { get; set; }
        public Nullable<bool> estdo { get; set; }
        public string numerofactura { get; set; }
        public string valorpagar { get; set; }
        public Nullable<System.DateTime> enviadafecha { get; set; }
        public string linkpago { get; set; }
    
        public virtual cliente cliente { get; set; }
    }
}
